#!/bin/bash

no_cache=
if [[ $NO_CACHE ]]; then
    no_cache=--no-cache
fi

: "${OSG_BUILD_IMAGE:=osg-htc/osg-build:v2}"
: "${OSG_BUILD_REPO:=opensciencegrid}"
: "${OSG_BUILD_BRANCH:=V2-branch}"
: "${DOCKER:=docker}"

git_describe=$(git describe --tags --always --dirty)

set -x
"${DOCKER}" build \
    $no_cache \
    --build-arg=OSG_BUILD_REPO="${OSG_BUILD_REPO}" \
    --build-arg=OSG_BUILD_BRANCH="${OSG_BUILD_BRANCH}" \
    --build-arg=RANDOM="${RANDOM}" \
    --tag "${OSG_BUILD_IMAGE}" \
    --label git.describe="$git_describe" \
    -f Dockerfile \
    "$@"
