name: Build and Push Docker image

on:
  push:
    branches: [ master ]
  repository_dispatch:
    types:
      - dispatch-build
  workflow_dispatch:
      
jobs:
  make-date-tag:
    runs-on: ubuntu-latest
    if: startsWith(github.repository, 'opensciencegrid/')
    outputs:
      dtag: ${{ steps.mkdatetag.outputs.dtag }}
    steps:
    - name: make date tag
      id: mkdatetag
      run: echo "dtag=$(date +%Y%m%d-%H%M)" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: [make-date-tag]
    if: startsWith(github.repository, 'opensciencegrid/')
    strategy:
      fail-fast: False
      matrix:
        dver: ['7', '8']
    steps:
    - uses: actions/checkout@v3

    - name: Generate tag list
      id: generate-tag-list
      env:
        REPO: ${{ matrix.repo }}
        TIMESTAMP: ${{ needs.make-date-tag.outputs.dtag }}
      run: |
        docker_repo=opensciencegrid/osg-build
        tag_list=()
        for registry in hub.opensciencegrid.org docker.io; do
          for version in ${{ matrix.dver }}; do
            tag_list+=($registry/$docker_repo:el$version)
          done
        done
        IFS=,
        echo "taglist=${tag_list[*]}" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.7.0

    - name: Log in to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Log in to OSG Harbor
      uses: docker/login-action@v2.2.0
      with:
        registry: hub.opensciencegrid.org
        username: ${{ secrets.OSG_HARBOR_ROBOT_USER }}
        password: ${{ secrets.OSG_HARBOR_ROBOT_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v4
      with:
        push: true
        build-args: EL_VER=${{ matrix.dver }}
        tags: "${{ steps.generate-tag-list.outputs.taglist }}"
